<?php 
/**
 * Abhay
 * 
 * PHP version 8
 * 
 * @category  Abhay
 * @package   Abhay_BlogManager
 * @author    Abhay Agrawal <abhay@gmail.com>
 * @copyright 2022 Copyright © Abhay
 * @license   See COPYING.txt for license details.
 * @link      https://github.com/abhay1198/blog-manager
 */
$enabled = $block->getConfigValue('abhay/general/enable'); ?>
<div>
    <?php if($enabled){ 
        $collection = $block->getBlogCollection();
    ?>
        <ul>
        <?php foreach ($collection as $blog): ?>
            <li>
                <div>
                    <h2><?php echo $blog->getBlogTitle(); ?></h2>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php } ?>
</div>

